### ISSUE TITLE
Rubocop raises exception for a weird but kinda valid syntax

### ISSUE THREAD

**Issue by wendelscardua** [backus/rubocop-rspec#408]
I managed to reproduce the problem with this script (using rubocop 0.48.1):
```ruby
def foobar
else
end
```
Ruby itself (2.2.5) gives only a warning for this file ("warning: else without rescue is useless"), but nonetheless this is a valid syntax for it.

Rubocop spits this stacktrace when running:

```
undefined method `join' for nil:NilClass
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/parser-2.4.0.0/lib/parser/builders/default.rb:1191:in `join_exprs'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/parser-2.4.0.0/lib/parser/builders/default.rb:1273:in `collection_map'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/parser-2.4.0.0/lib/parser/builders/default.rb:1026:in `begin_body'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/parser-2.4.0.0/lib/parser/ruby22.rb:3387:in `_reduce_9'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/parser-2.4.0.0/lib/parser/base.rb:162:in `parse'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/parser-2.4.0.0/lib/parser/base.rb:209:in `tokenize'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/processed_source.rb:99:in `tokenize'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/processed_source.rb:94:in `parse'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/processed_source.rb:36:in `initialize'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/processed_source.rb:17:in `new'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/processed_source.rb:17:in `from_file'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/runner.rb:324:in `get_processed_source'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/runner.rb:100:in `block in file_offenses'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/runner.rb:111:in `file_offense_cache'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/runner.rb:99:in `file_offenses'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/runner.rb:90:in `process_file'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/runner.rb:65:in `each'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/runner.rb:65:in `reduce'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/runner.rb:65:in `each_inspected_file'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/runner.rb:57:in `inspect_files'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/runner.rb:36:in `run'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/cli.rb:72:in `execute_runner'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/lib/rubocop/cli.rb:27:in `run'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/bin/rubocop:13:in `block in <top (required)>'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/wendel/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rubocop-0.48.1/bin/rubocop:12:in `<top (required)>'
/home/wendel/.rbenv/versions/2.2.5/bin/rubocop:22:in `load'
/home/wendel/.rbenv/versions/2.2.5/bin/rubocop:22:in `<main>'
Inspecting 1 file


0 files inspected, no offenses detected
```

(this syntax wasn't intentional, my Emacs uses rubocop for autoformatting and exploded while I was in the middle of editing an `if` statement)

**Comment by wendelscardua** [comment]
Oops, reported on the wrong project by mistake, closing this one...
