### ISSUE TITLE
`Rails/Blank` and `Rails/Present` throw an error no receiver is specified in `if` and `unless` statements

### ISSUE THREAD

**Issue by dark-panda** [backus/rubocop-rspec#427]
The following causes `Rails/Blank` and `Rails/Present` to bomb out:

```ruby
class Foo
  def example_a
    'example_a' if present?
  end

  def example_b
    'example_b' unless present?
  end

  def example_c
    'example_c' if blank?
  end

  def example_d
    'example_d' unless blank?
  end
end
```

Depending on your configuration, one of those will cause errors similar to the following:

```
% bundle exec rubocop -d rails_blank_and_present_example.rb
For /example: configuration from /example/.rubocop.yml
Default configuration from /example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/config/default.yml
Inheriting configuration from /example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/config/enabled.yml
Inheriting configuration from /example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/config/disabled.yml
Inspecting 1 file
Scanning /example/rails_blank_and_present_example.rb
An error occurred while Rails/Blank cop was inspecting /example/rails_blank_and_present_example.rb:8:4.
undefined method `source' for nil:NilClass
/example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/rails/blank.rb:101:in `block in on_if'
/example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/rails/blank.rb:63:in `unless_present?'
/example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/rails/blank.rb:95:in `on_if'
/example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/commissioner.rb:44:in `block (2 levels) in on_if'
/example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/commissioner.rb:106:in `with_cop_error_handling'
/example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/commissioner.rb:43:in `block in on_if'
/example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/commissioner.rb:42:in `each'
/example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/commissioner.rb:42:in `on_if'
/example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/ast/traversal.rb:95:in `on_def'
/example/.bundle/ruby/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/commissioner.rb:48:in `on_def'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
<snip>
```

In the example code, we're using the `#blank?` and `#present?` methods that we inherit from the ActiveSupport core extensions and there is no explicit receiver.

**Comment by backus** [comment]
This is not our cop. You'll want to report this to rubocop proper

**Comment by dark-panda** [comment]
I'm an idiot -- I submitted this without looking at the URL for the tab I was on. And worse yet, it appears to be fixed already -- I was searching within rubocop-rspec issues rather than rubocop issues and now I see the existing report along with the fix. Basically this is a case of me not paying attention to all of the things. :/ Sorry for the time waster.

**Comment by backus** [comment]
No problem 😄
