### ISSUE TITLE
Problems disabling/configuring a cop

### ISSUE THREAD

**Issue by AlexVPopov** [backus/rubocop-rspec#452]
I have a problem, disabling `RSpec/MultipleExpectations`. I some some funny behavior, when trying to configure/disable the cop via `.rubocop.yml`.

This:

```yaml
RSpec/MultipleExpectations:
  Max: 5
```

works. I see fewer violations and the proper counters at the end of the lines in the report (e.g. `RSpec/MultipleExpectations: Example has too many expectations [8/5].`)

This:

```yaml
RSpec/MultipleExpectations:
  Enabled: false
```

doesn't work, the cop is not disabled, violations are still reported.

However, this:

```yaml
RSpec:
  MultipleExpectations:
    Enabled: false
```

works... with a twist:

```bash

$ rubocop -D --only RSpec/MultipleExpectations
Inspecting 100 files


0 files inspected, no offenses detected
key not found: "Enabled"
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/config.rb:436:in `fetch'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/config.rb:436:in `enable_cop?'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/config.rb:118:in `block in initialize'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/config.rb:208:in `for_cop'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/registry.rb:119:in `block in enabled'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/registry.rb:138:in `select'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/registry.rb:138:in `select'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/registry.rb:118:in `enabled'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/team.rb:47:in `cops'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/team.rb:137:in `validate_config'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cop/team.rb:25:in `initialize'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:257:in `new'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:257:in `inspect_file'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:205:in `block in do_inspection_loop'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:237:in `block in iterate_until_no_changes'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:230:in `loop'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:230:in `iterate_until_no_changes'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:201:in `do_inspection_loop'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:111:in `block in file_offenses'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:121:in `file_offense_cache'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:109:in `file_offenses'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:100:in `process_file'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:75:in `each'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:75:in `reduce'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:75:in `each_inspected_file'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:67:in `inspect_files'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/runner.rb:39:in `run'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cli.rb:82:in `execute_runner'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cli.rb:28:in `run'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/bin/rubocop:13:in `block in <top (required)>'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/Users/apopov/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/bin/rubocop:12:in `<top (required)>'
/Users/apopov/.rbenv/versions/2.4.1/bin/rubocop:22:in `load'
/Users/apopov/.rbenv/versions/2.4.1/bin/rubocop:22:in `<main>'
```

**Comment by AlexVPopov** [comment]
Sorry, the last configuration doesn't work, it just breaks `rubocop`, as the result is the same regardless of the options.

**Comment by AlexVPopov** [comment]
O.K., it seems there was an error in my setup, as I tried yet again and it worked, sorry for the confusion.

**Comment by bobmazanec** [comment]
@AlexVPopov do you remember what the error in your setup was?
I started getting the behavior you're describing after upgrading to rubocop 0.49.0 from 0.47.1
TIA

**Comment by AlexVPopov** [comment]
@bobmazanec unfortunately I have totally forgotten what the error was, sorry 🤷‍♂️

**Comment by bobmazanec** [comment]
I had to try
Thanks & HNY 😃
