### ISSUE TITLE
An error occurred while RSpec/DescribedClass cop

### ISSUE THREAD

**Issue by mensfeld** [backus/rubocop-rspec#541]
Steps to reproduce:

1. Clone this repo: https://github.com/mensfeld/broken-rubocop-rspec
2. Bundle
3. bundle exec rubocop

See:

```bash
Inspecting 2 files
.An error occurred while RSpec/DescribedClass cop was inspecting /home/user/example/spec/broken_spec.rb:1:0.
To see the complete backtrace run rubocop -d.
C

Offenses:

spec/broken_spec.rb:1:1: C: RSpec/EmptyExampleGroup: Empty example group detected.
describe Broken do
^^^^^^^^^^^^^^^

2 files inspected, 1 offense detected

1 error occurred:
An error occurred while RSpec/DescribedClass cop was inspecting /home/user/example/spec/broken_spec.rb:1:0.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.0 x86_64-linux)
```

**Comment by mensfeld** [comment]
With a debug:

```bash
[broken-rubocop-rspec (master)]$ be rubocop -d
For /home/user/broken-rubocop-rspec: configuration from /home/user/broken-rubocop-rspec/.rubocop.yml
configuration from /home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-rspec-1.22.1/config/default.yml
configuration from /home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-rspec-1.22.1/config/default.yml
Default configuration from /home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/config/default.yml
Inheriting configuration from /home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/config/enabled.yml
Inheriting configuration from /home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/config/disabled.yml
Inspecting 2 files
Scanning /home/user/broken-rubocop-rspec/Gemfile
.Scanning /home/user/broken-rubocop-rspec/spec/broken_spec.rb
An error occurred while RSpec/DescribedClass cop was inspecting /home/user/broken-rubocop-rspec/spec/broken_spec.rb:1:0.
undefined method `block_type?' for nil:NilClass
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-rspec-1.22.1/lib/rubocop/cop/rspec/described_class.rb:107:in `skippable_block?'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-rspec-1.22.1/lib/rubocop/cop/rspec/described_class.rb:103:in `scope_change?'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-rspec-1.22.1/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-rspec-1.22.1/lib/rubocop/cop/rspec/described_class.rb:59:in `on_block'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:44:in `block (2 levels) in on_block'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:109:in `with_cop_error_handling'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:43:in `block in on_block'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:42:in `each'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:42:in `on_block'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/traversal.rb:12:in `walk'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/commissioner.rb:60:in `investigate'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/team.rb:114:in `investigate'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/team.rb:102:in `offenses'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/team.rb:44:in `inspect_file'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:258:in `inspect_file'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:205:in `block in do_inspection_loop'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:237:in `block in iterate_until_no_changes'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:230:in `loop'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:230:in `iterate_until_no_changes'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:201:in `do_inspection_loop'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:111:in `block in file_offenses'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:121:in `file_offense_cache'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:109:in `file_offenses'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:100:in `process_file'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:75:in `each'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:75:in `reduce'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:75:in `each_inspected_file'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:67:in `inspect_files'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/runner.rb:39:in `run'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/cli.rb:150:in `execute_runner'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/cli.rb:78:in `execute_runners'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/lib/rubocop/cli.rb:38:in `run'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/bin/rubocop:13:in `block in <top (required)>'
/home/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/home/user/.rvm/gems/ruby-2.4.0/gems/rubocop-0.52.1/bin/rubocop:12:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.4.0/bin/rubocop:22:in `load'
/home/user/.rvm/gems/ruby-2.4.0/bin/rubocop:22:in `<main>'
/home/user/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
C

Offenses:

spec/broken_spec.rb:1:1: C: RSpec/EmptyExampleGroup: Empty example group detected.
describe Broken do
^^^^^^^^^^^^^^^

2 files inspected, 1 offense detected

1 error occurred:
An error occurred while RSpec/DescribedClass cop was inspecting /home/user/broken-rubocop-rspec/spec/broken_spec.rb:1:0.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.0 x86_64-linux)
Finished in 0.22132196600023235 seconds

```
