### ISSUE TITLE
Error from FactoryBot/StaticAttributeDefinedDynamically

### ISSUE THREAD

**Issue by bquorning** [backus/rubocop-rspec#563]
Inspecting this file gives me an error:

```rb
FactoryBot.define do
  factory :foo do
    bar {}
  end
end
```

Partial stacktrace

```
undefined method `recursive_literal?' for nil:NilClass
.../rubocop-rspec-1.23.0/lib/rubocop/cop/rspec/factory_bot/static_attribute_defined_dynamically.rb:62:in `static?'
.../rubocop-rspec-1.23.0/lib/rubocop/cop/rspec/factory_bot/static_attribute_defined_dynamically.rb:45:in `block (2 levels) in on_block'
.../rubocop-rspec-1.23.0/lib/rubocop/cop/rspec/factory_bot/static_attribute_defined_dynamically.rb:45:in `each'
.../rubocop-rspec-1.23.0/lib/rubocop/cop/rspec/factory_bot/static_attribute_defined_dynamically.rb:45:in `none?'
.../rubocop-rspec-1.23.0/lib/rubocop/cop/rspec/factory_bot/static_attribute_defined_dynamically.rb:45:in `block in on_block'
.../rubocop-rspec-1.23.0/lib/rubocop/cop/rspec/factory_bot/static_attribute_defined_dynamically.rb:42:in `each'
.../rubocop-rspec-1.23.0/lib/rubocop/cop/rspec/factory_bot/static_attribute_defined_dynamically.rb:42:in `on_block'
```

Using rubocop-rspec v1.23.0 and rubocop v0.52.1:

```
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.2 x86_64-darwin15)
```

cc @abrom

**Comment by abrom** [comment]
Good find @bquorning 👍 I'll put a PR together

**Comment by abrom** [comment]
Just thinking about the ideal result here.. I suspect it would identify that as an offense.. Autocorrecting with `bar nil`

Thoughts?

**Comment by bquorning** [comment]
Yeah, I guess. `bar` is defined by a dynamic attribute that will always return `nil`… which makes it a static attribute. So `bar nil` makes sense. 👍
